# CREATE DATABASE cids DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
USE cids;
CREATE TABLE T_GP_USER (
  F_USER_ID VARCHAR(32) NOT NULL COMMENT 'id',
  F_LOGIN_NAME VARCHAR(30) NOT NULL COMMENT '登录名称',
  F_PASSWORD VARCHAR(32) NOT NULL COMMENT '登录密码',
  F_REAL_NAME VARCHAR(20) COMMENT '真实姓名',
  F_STATUS VARCHAR(10) COMMENT '用户状态',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_USER_ID) )COMMENT '用户信息';

CREATE TABLE T_GP_ROLE (
  F_ROLE_ID VARCHAR(30) NOT NULL COMMENT 'id',
  F_ROLE_NAME VARCHAR(30) COMMENT '角色名称',
  F_ROLE_DESC VARCHAR(30) COMMENT '角色描述',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_ROLE_ID) )COMMENT '用户角色';

CREATE TABLE T_GP_USER_ROLE (
  F_USER_ID VARCHAR(32) NOT NULL COMMENT '用户id',
  F_ROLE_ID VARCHAR(30) NOT NULL COMMENT '角色id',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间')COMMENT '用户角色关联表';

CREATE TABLE T_GP_PERMISSION (
  F_PERMISSION_ID INT(5) NOT NULL AUTO_INCREMENT COMMENT 'id',
  F_PERMISSION_NAME VARCHAR(30) COMMENT '权限名称',
  F_PERMISSION_DESC VARCHAR(30) COMMENT '权限描述',
  F_PERMISSION_URL VARCHAR(100) NOT NULL COMMENT '权限地址',
  F_PARENT_ID VARCHAR(30) NOT NULL COMMENT '父节点',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_PERMISSION_ID) )COMMENT '用户权限';

CREATE TABLE T_GP_ROLE_PERMISSION (
  F_ROLE_ID VARCHAR(30) NOT NULL COMMENT '角色id',
  F_PERMISSION_ID INT(5) NOT NULL COMMENT '权限id',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间')COMMENT '角色权限关联表';
#############################################################################
#############################################################################
CREATE TABLE T_GP_APPLICATION(
  F_APP_ID INT(5) NOT NULL AUTO_INCREMENT COMMENT 'id',
  F_APP_NAME VARCHAR(50) COMMENT '应用名称',
  F_STORAGE_PATH VARCHAR(200) COMMENT 'war包存储路径',
  F_VIEW_NAME VARCHAR(50) COMMENT '视图名称',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_APP_ID) ) COMMENT '应用信息';

CREATE TABLE T_GP_DEPLOY_HOST(
  F_HOST_ID INT(5) NOT NULL AUTO_INCREMENT COMMENT 'id',
  F_HOST_NAME VARCHAR(30) COMMENT '主机别名',
  F_HOST_IP VARCHAR(20) COMMENT '主机ip',
  F_LOGIN_NAME VARCHAR(30) COMMENT '访问用户名',
  F_PASSWORD VARCHAR(50) COMMENT '访问密码',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_HOST_ID) ) COMMENT '目标主机';

CREATE TABLE T_GP_DEPLOY_SERVER(
  F_SERVER_ID INT(5) NOT NULL AUTO_INCREMENT COMMENT 'id',
  F_HOST_ID INT(5) NOT NULL COMMENT '主机id',
  F_APP_ID INT(5) NOT NULL COMMENT '应用id',
  F_SERVER_NAME VARCHAR(30) COMMENT '应用服务器别名',
  F_STORAGE_PATH VARCHAR(200) NOT NULL COMMENT '部署路径',
  F_PROTOCOL VARCHAR(10) COMMENT '请求协议',
  F_PORT VARCHAR(10) NOT NULL COMMENT '端口号',
  F_CONTEX_TPATH VARCHAR(10) COMMENT '项目根路径',
  F_CREATE_TIMESTAMP TIMESTAMP COMMENT '创建时间',
  F_UPDATE_TIMESTAMP TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (F_SERVER_ID) ) COMMENT '目标应用服务器';